import { db } from "../config/firebase.js";
import { ensureZeroStockOptionEntry } from "../controllers/stockOptionsController.js";
import { ensureMissingZoneStockEntry } from "../controllers/zoneStockController.js";
import { ensureCashClosureEntry } from "../controllers/cashClosureController.js";
import { getSourceOutletSummary } from "../controllers/outletSummaryController.js";

const ZONES = ["Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5"];
const DAILY_ENTRY_FINAL_MINUTES = (23 * 60) + 15;
const INVENTORY_FINAL_MINUTES = (23 * 60) + 45;

const getIndiaDate = (offsetDays = 0) => {
  const indiaNow = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }));
  indiaNow.setDate(indiaNow.getDate() + offsetDays);
  return indiaNow.toISOString().slice(0, 10);
};

const getActiveOutlets = async () => {
  const snapshot = await db.collection("outlets").get();
  return snapshot.docs
    .map((doc) => doc.data())
    .filter((outlet) => outlet?.status === "Active" && outlet?.id);
};

const getDayDocuments = async (collection, date) => {
  const snapshot = await db.collection(collection).where("date", "==", date).get();
  return snapshot.docs;
};

const getPreferredDayDocument = (docs) => {
  const rows = (docs || []).map((doc) => ({ doc, data: doc.data() || {} }));
  return rows.sort((left, right) => {
    const leftAuto = Boolean(left.data.autoGenerated);
    const rightAuto = Boolean(right.data.autoGenerated);
    if (leftAuto !== rightAuto) return Number(leftAuto) - Number(rightAuto);
    const leftTime = left.data.updatedAt?.toMillis?.() || left.data.createdAt?.toMillis?.() || 0;
    const rightTime = right.data.updatedAt?.toMillis?.() || right.data.createdAt?.toMillis?.() || 0;
    return rightTime - leftTime;
  })[0]?.doc || null;
};

const mergeDayValues = (docs, valuesField) => {
  const values = {};
  (docs || []).forEach((doc) => {
    Object.entries(doc.data()?.[valuesField] || {}).forEach(([key, rawValue]) => {
      const currentValue = Number(values[key]) || 0;
      const nextValue = Number(rawValue) || 0;
      if (values[key] === undefined || nextValue !== 0 || currentValue === 0) values[key] = rawValue;
    });
  });
  return values;
};

const ensureZeroMapValues = async ({ collection, date, valuesField, outletKeys }) => {
  const dayDocs = await getDayDocuments(collection, date);
  const existingDoc = getPreferredDayDocument(dayDocs);
  const values = mergeDayValues(dayDocs, valuesField);
  let changed = false;

  outletKeys.forEach((key) => {
    if (values[key] === undefined) {
      values[key] = 0;
      changed = true;
    }
  });

  if (!changed) return;

  const payload = {
    date,
    [valuesField]: values,
    updatedAt: new Date(),
  };

  if (existingDoc) {
    await existingDoc.ref.set(payload, { merge: true });
  } else {
    await db.collection(collection).doc(date).set({ ...payload, autoGenerated: true, createdAt: new Date() });
  }
};

const ensureZeroNeccRates = async (date, outletIds) => {
  const snapshot = await db.collection("neccRates").where("date", "==", date).get();
  const existingOutletIds = new Set(snapshot.docs.map((doc) => String(doc.data()?.outletId || doc.data()?.outlet || "")));

  await Promise.all(outletIds.map(async (outletId) => {
    if (existingOutletIds.has(String(outletId))) return;

    await db.collection("neccRates").doc(`auto_${date}_${outletId}`).set({
      date,
      outletId,
      outlet: outletId,
      rate: "₹0.00 per egg",
      rateValue: 0,
      form_remark: "",
      autoGenerated: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }));
};

const toNumber = (value) => {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : 0;
};

// The nightly job is the final record for the day.  Keep one date document per
// collection, but merge every active outlet's source-project value into it.
const saveFinalMapValues = async ({ collection, date, valuesField, values, outletIds = [], onlyMissing = false }) => {
  const dayDocs = await getDayDocuments(collection, date);
  const preferredDoc = getPreferredDayDocument(dayDocs);
  const existingValues = mergeDayValues(dayDocs, valuesField);
  const mergedValues = { ...existingValues };
  Object.entries(values).forEach(([outletId, val]) => {
    const newVal = toNumber(val);
    const oldVal = toNumber(existingValues[outletId]);
    
    if (onlyMissing) {
      if (existingValues[outletId] === undefined) {
        mergedValues[outletId] = newVal;
      }
    } else {
      // Prioritize the new value from the source project, BUT do not overwrite 
      // an existing manual non-zero entry with an automated zero.
      if (newVal !== 0 || oldVal === 0 || existingValues[outletId] === undefined) {
        mergedValues[outletId] = newVal;
      }
    }
  });
  outletIds.forEach((outletId) => {
    if (mergedValues[outletId] === undefined) mergedValues[outletId] = 0;
  });
  const payload = {
    date,
    [valuesField]: mergedValues,
    total: Object.values(mergedValues).reduce((sum, value) => sum + toNumber(value), 0),
    finalSourceSync: true,
    sourceSyncedAt: new Date(),
    updatedAt: new Date(),
  };

  if (preferredDoc) {
    await preferredDoc.ref.set(payload, { merge: true });
  } else {
    await db.collection(collection).doc(date).set({ ...payload, createdAt: new Date() });
  }
};

const saveFinalNeccRates = async (date, values) => {
  const snapshot = await db.collection("neccRates").where("date", "==", date).get();
  const byOutletId = new Map();
  snapshot.docs.forEach((doc) => {
    const outletId = String(doc.data()?.outletId || doc.data()?.outlet || "");
    const current = byOutletId.get(outletId);
    if (!current || Boolean(current.data()?.autoGenerated)) byOutletId.set(outletId, doc);
  });

  await Promise.all(Object.entries(values).map(async ([outletId, rawRate]) => {
    const rateValue = toNumber(rawRate);
    const payload = {
      date,
      outletId,
      outlet: outletId,
      rateValue,
      rate: `₹${rateValue.toFixed(3)} per egg`,
      finalSourceSync: true,
      sourceSyncedAt: new Date(),
      updatedAt: new Date(),
    };
    const existingDoc = byOutletId.get(String(outletId));
    if (existingDoc) {
      await existingDoc.ref.set(payload, { merge: true });
    } else {
      await db.collection("neccRates").doc(`final_${date}_${outletId}`).set({ ...payload, createdAt: new Date() });
    }
  }));
};

const saveFinalRemarks = async (date, outletIds) => {
  const dayDocs = await getDayDocuments("remarks", date);
  const preferredDoc = getPreferredDayDocument(dayDocs);
  const existingRemarks = dayDocs.reduce((result, doc) => ({
    ...result,
    ...(doc.data()?.remarks || {}),
    ...(doc.data()?.outlets || {}),
  }), {});
  const remarks = { ...existingRemarks };
  outletIds.forEach((outletId) => {
    if (remarks[outletId] === undefined) remarks[outletId] = "";
  });
  const payload = {
    date,
    outlets: remarks,
    // Keep this compatibility map because older Data Entry records read it.
    remarks,
    finalSourceSync: true,
    sourceSyncedAt: new Date(),
    updatedAt: new Date(),
  };

  if (preferredDoc) {
    await preferredDoc.ref.set(payload, { merge: true });
  } else {
    await db.collection("remarks").doc(date).set({ ...payload, createdAt: new Date() });
  }
};

const saveDailyEntrySyncStatus = async (date, outletStatuses, startedAt) => {
  const completedAt = new Date();
  await db.collection("dailyEntrySyncStatus").doc(date).set({
    date,
    outlets: outletStatuses,
    startedAt,
    completedAt,
    durationMs: completedAt.getTime() - startedAt.getTime(),
    updatedAt: completedAt,
  }, { merge: true });
};

const ensureDailyEntryDefaults = async (date) => {
  const outlets = await getActiveOutlets();
  if (!outlets.length) return;
  const startedAt = new Date();
  const sourceResults = await Promise.allSettled(outlets.map(async (outlet) => {
    const sourceOutlet = outlet.area || outlet.name || outlet.id;
    return { outletId: outlet.id, summary: await getSourceOutletSummary(sourceOutlet, date) };
  }));

  const values = {
    sales: {}, cash: {}, digital: {}, damages: {}, incentive: {},
    foodAllowance: {}, advance: {}, neccRate: {},
  };
  const outletStatuses = {};

  sourceResults.forEach((result, index) => {
    const outlet = outlets[index];
    const outletId = outlet.id;
    if (result.status === "rejected") {
      outletStatuses[outletId] = {
        status: "pending",
        error: String(result.reason?.message || "Source data could not be read"),
        updatedAt: new Date().toISOString(),
      };
      return;
    }

    const { summary } = result.value;
    const available = summary.syncAvailability || {};
    if (available.sales) values.sales[outletId] = toNumber(summary.salesQty);
    if (available.neccRate) values.neccRate[outletId] = toNumber(summary.neccRate);
    if (available.cash) values.cash[outletId] = toNumber(summary.cashPayment ?? summary.cashHandover);
    if (available.digital) values.digital[outletId] = toNumber(summary.digitalPayment);
    if (available.damages) values.damages[outletId] = toNumber(summary.damage);
    if (available.incentive) values.incentive[outletId] = toNumber(summary.incentive);
    if (available.foodAllowance) values.foodAllowance[outletId] = toNumber(summary.foodAllowance);

    const pendingFields = ["sales", "neccRate", "cash", "digital", "damages", "incentive", "foodAllowance"]
      .filter((field) => !available[field]);
    outletStatuses[outletId] = {
      status: pendingFields.length ? "partial" : "saved",
      pendingFields,
      updatedAt: new Date().toISOString(),
    };
  });

  await Promise.all([
    saveFinalMapValues({ collection: "dailySales", date, valuesField: "outlets", values: values.sales }),
    saveFinalMapValues({ collection: "cashPayments", date, valuesField: "outlets", values: values.cash }),
    saveFinalMapValues({ collection: "digitalPayments", date, valuesField: "outlets", values: values.digital }),
    saveFinalMapValues({ collection: "dailyDamages", date, valuesField: "damages", values: values.damages }),
    saveFinalMapValues({ collection: "incentive", date, valuesField: "outlets", values: values.incentive }),
    // The source project has no advance value; retain a manual value if there
    // is one, otherwise save the required zero for every outlet.
    saveFinalMapValues({ collection: "advance", date, valuesField: "outlets", values: values.advance, outletIds: outlets.map((outlet) => outlet.id), onlyMissing: true }),
    saveFinalMapValues({ collection: "foodAllowance", date, valuesField: "outlets", values: values.foodAllowance }),
    saveFinalNeccRates(date, values.neccRate),
    saveFinalRemarks(date, outlets.map((outlet) => outlet.id)),
    saveDailyEntrySyncStatus(date, outletStatuses, startedAt),
  ]);

  const saved = Object.values(outletStatuses).filter((item) => item.status === "saved").length;
  const partial = Object.values(outletStatuses).filter((item) => item.status === "partial").length;
  const pending = Object.values(outletStatuses).filter((item) => item.status === "pending").length;
  console.info(`Daily entry final sync ${date}: ${saved} saved, ${partial} partial, ${pending} pending in ${Date.now() - startedAt.getTime()}ms.`);
};

let lastDailyEntryDate = "";
let lastInventoryDate = "";

const getIndiaNow = () => new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }));

const runDailyEntryDefaults = async (date) => {
  if (lastDailyEntryDate === date) return false;
  await ensureDailyEntryDefaults(date);
  lastDailyEntryDate = date;
  return true;
};

const runInventoryDefaults = async (date) => {
  if (lastInventoryDate === date) return false;
  // Keep the final-save order deterministic: create a zero stock-option row
  // only when the admin has not entered one, calculate inventory from that
  // saved stock, then create the cash closure with any missing manual value as
  // zero. Each helper exits without changing an existing manual record.
  await Promise.all(ZONES.map((zone) => ensureZeroStockOptionEntry(zone, date)));
  await Promise.all(ZONES.map((zone) => ensureMissingZoneStockEntry(zone, date)));
  await Promise.all(ZONES.map((zone) => ensureCashClosureEntry(zone, date)));
  lastInventoryDate = date;
  return true;
};

export const runMidnightDefaults = async (date = getIndiaDate(-1)) => {
  // Cash closure consumes Data Entry's verified final-sync status, so this
  // recovery path must never start inventory/cash closure before that sync.
  const dailyProcessed = await runDailyEntryDefaults(date);
  const inventoryProcessed = await runInventoryDefaults(date);
  return dailyProcessed || inventoryProcessed;
};

export const startMidnightDefaultsScheduler = (onComplete = null) => {
  const run = async () => {
    try {
      const now = getIndiaNow();
      const minutes = now.getHours() * 60 + now.getMinutes();
      const today = getIndiaDate();
      const yesterday = getIndiaDate(-1);
      let processed = false;

      if (minutes < DAILY_ENTRY_FINAL_MINUTES) {
        processed = await runMidnightDefaults(yesterday);
      } else {
        if (await runDailyEntryDefaults(today)) processed = true;
        if (minutes >= INVENTORY_FINAL_MINUTES && await runInventoryDefaults(today)) processed = true;
      }

      if (processed && typeof onComplete === "function") onComplete();
    } catch (error) {
      console.error("Scheduled defaults failed:", error.message);
    }
  };

  run();
  setInterval(run, 60_000);
};
