import { db } from "../config/firebase.js";
import { ensureZeroStockOptionEntry } from "../controllers/stockOptionsController.js";
import { ensureMissingZoneStockEntry } from "../controllers/zoneStockController.js";
import { ensureCashClosureEntry } from "../controllers/cashClosureController.js";

const ZONES = ["Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5"];

const getIndiaDate = (offsetDays = 0) => {
  const indiaNow = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }));
  indiaNow.setDate(indiaNow.getDate() + offsetDays);
  return indiaNow.toISOString().slice(0, 10);
};

const getActiveOutlets = async () => {
  const snapshot = await db.collection("outlets").get();
  return snapshot.docs
    .map((doc) => doc.data())
    .filter((outlet) => outlet?.status === "Active" && outlet?.id);
};

const getDayDocument = async (collection, date) => {
  const snapshot = await db.collection(collection).where("date", "==", date).limit(1).get();
  return snapshot.docs[0] || null;
};

const ensureZeroMapValues = async ({ collection, date, valuesField, outletKeys }) => {
  const existingDoc = await getDayDocument(collection, date);
  const existingData = existingDoc?.data() || {};
  const values = { ...(existingData[valuesField] || {}) };
  let changed = false;

  outletKeys.forEach((key) => {
    if (values[key] === undefined) {
      values[key] = 0;
      changed = true;
    }
  });

  if (!changed) return;

  const payload = {
    date,
    [valuesField]: values,
    updatedAt: new Date(),
  };

  if (existingDoc) {
    await existingDoc.ref.set(payload, { merge: true });
  } else {
    await db.collection(collection).doc(date).set({ ...payload, autoGenerated: true, createdAt: new Date() });
  }
};

const ensureZeroNeccRates = async (date, outletIds) => {
  const snapshot = await db.collection("neccRates").where("date", "==", date).get();
  const existingOutletIds = new Set(snapshot.docs.map((doc) => String(doc.data()?.outletId || doc.data()?.outlet || "")));

  await Promise.all(outletIds.map(async (outletId) => {
    if (existingOutletIds.has(String(outletId))) return;

    await db.collection("neccRates").doc(`auto_${date}_${outletId}`).set({
      date,
      outletId,
      outlet: outletId,
      rate: "₹0.00 per egg",
      rateValue: 0,
      form_remark: "",
      autoGenerated: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }));
};

const ensureDailyEntryDefaults = async (date) => {
  const outlets = await getActiveOutlets();
  if (!outlets.length) return;

  const salesDoc = await getDayDocument("dailySales", date);
  const sales = { ...(salesDoc?.data()?.outlets || {}) };
  const zeroSalesOutlets = [];
  let salesChanged = false;

  outlets.forEach((outlet) => {
    const outletId = outlet.id;
    if (sales[outletId] === undefined) {
      sales[outletId] = 0;
      salesChanged = true;
    }
    if (!(Number(sales[outletId]) > 0)) zeroSalesOutlets.push(outlet);
  });

  if (salesChanged) {
    const payload = {
      date,
      outlets: sales,
      total: Object.values(sales).reduce((sum, value) => sum + (Number(value) || 0), 0),
      updatedAt: new Date(),
    };
    if (salesDoc) {
      await salesDoc.ref.set(payload, { merge: true });
    } else {
      await db.collection("dailySales").doc(date).set({ ...payload, autoGenerated: true, createdAt: new Date() });
    }
  }

  const outletIds = zeroSalesOutlets.map((outlet) => outlet.id);
  const outletAreas = zeroSalesOutlets.map((outlet) => outlet.area || outlet.name || outlet.id);
  if (!outletIds.length) return;

  await Promise.all([
    ensureZeroMapValues({ collection: "cashPayments", date, valuesField: "outlets", outletKeys: outletIds }),
    ensureZeroMapValues({ collection: "digitalPayments", date, valuesField: "outlets", outletKeys: outletIds }),
    ensureZeroMapValues({ collection: "dailyDamages", date, valuesField: "damages", outletKeys: outletAreas }),
    ensureZeroMapValues({ collection: "incentive", date, valuesField: "outlets", outletKeys: outletIds }),
    ensureZeroMapValues({ collection: "advance", date, valuesField: "outlets", outletKeys: outletIds }),
    ensureZeroMapValues({ collection: "foodAllowance", date, valuesField: "outlets", outletKeys: outletIds }),
    ensureZeroNeccRates(date, outletIds),
  ]);
};

let lastDailyEntryDate = "";
let lastInventoryDate = "";

const getIndiaNow = () => new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" }));

const runDailyEntryDefaults = async (date) => {
  if (lastDailyEntryDate === date) return false;
  await ensureDailyEntryDefaults(date);
  lastDailyEntryDate = date;
  return true;
};

const runInventoryDefaults = async (date) => {
  if (lastInventoryDate === date) return false;
  await Promise.all(ZONES.map((zone) => ensureZeroStockOptionEntry(zone, date)));
  await Promise.all(ZONES.map((zone) => ensureMissingZoneStockEntry(zone, date)));
  await Promise.all(ZONES.map((zone) => ensureCashClosureEntry(zone, date)));
  lastInventoryDate = date;
  return true;
};

export const runMidnightDefaults = async (date = getIndiaDate(-1)) => {
  const [dailyProcessed, inventoryProcessed] = await Promise.all([
    runDailyEntryDefaults(date),
    runInventoryDefaults(date),
  ]);
  return dailyProcessed || inventoryProcessed;
};

export const startMidnightDefaultsScheduler = (onComplete = null) => {
  const run = async () => {
    try {
      const now = getIndiaNow();
      const minutes = now.getHours() * 60 + now.getMinutes();
      const today = getIndiaDate();
      const yesterday = getIndiaDate(-1);
      let processed = false;

      if (minutes < (23 * 60 + 30)) {
        processed = await runMidnightDefaults(yesterday);
      } else {
        if (await runDailyEntryDefaults(today)) processed = true;
        if (minutes >= (23 * 60 + 45) && await runInventoryDefaults(today)) processed = true;
      }

      if (processed && typeof onComplete === "function") onComplete();
    } catch (error) {
      console.error("Scheduled defaults failed:", error.message);
    }
  };

  run();
  setInterval(run, 60_000);
};
