const API_URL = import.meta.env.VITE_API_URL;

import React, { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import Topbar from "../components/Topbar";
import Dailyheader from "../components/Dailyheader";
import DailyTable from "../components/DailyTable";
import { getThisWeekRange } from "../utils/dateRange";

const getOutletLabel = (outlet) => outlet?.area || outlet?.name || outlet?.id || "";

const getAuthHeaders = () => {
  const token = localStorage.getItem("token");
  return token ? { Authorization: `Bearer ${token}` } : {};
};

const normalizeOutletKey = (value) => String(value || "").trim().toLowerCase();

const getRecordPriority = (record) => {
  if (record?.finalSourceSync) return 3;
  return record?.autoGenerated ? 1 : 2;
};

const getRecordTime = (record) => {
  const value = record?.updatedAt || record?.createdAt || record?.date;
  if (value?.seconds ?? value?._seconds) return Number(value.seconds ?? value._seconds) * 1000;
  const time = new Date(value).getTime();
  return Number.isNaN(time) ? 0 : time;
};

const runWithConcurrency = async (tasks, limit = 4) => {
  const results = new Array(tasks.length);
  let nextIndex = 0;

  const worker = async () => {
    while (nextIndex < tasks.length) {
      const currentIndex = nextIndex;
      nextIndex += 1;
      results[currentIndex] = await tasks[currentIndex]();
    }
  };

  await Promise.all(Array.from({ length: Math.min(limit, tasks.length) }, worker));
  return results;
};

const formatDateDMY = (iso) => {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  return `${String(date.getDate()).padStart(2, "0")}-${String(date.getMonth() + 1).padStart(2, "0")}-${date.getFullYear()}`;
};

function RevenueAnalytics({ rows }) {
  const chartData = useMemo(() => {
    return rows.map((row) => ({
      date: formatDateDMY(row.date),
      total: Number(row.total) || 0,
    }));
  }, [rows]);

  if (!chartData.length) return null;

  return (
    <div className="mt-10">
      <h1 className="text-2xl font-bold mb-6">Daily Revenue Analytics</h1>

      <div className="ml-4 bg-white shadow rounded-xl p-6">
        <h2 className="font-semibold mb-4">Revenue Trend by Date</h2>
        <div style={{ width: "100%", height: 260 }}>
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="date" />
              <YAxis />
              <Tooltip formatter={(value) => `₹${Number(value).toLocaleString("en-IN")}`} />
              <Line
                type="monotone"
                dataKey="total"
                stroke="#f97316"
                strokeWidth={3}
                dot={{ r: 5 }}
                activeDot={{ r: 7 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
}

export default function DailyRevenue() {
  const defaultWeekRange = useMemo(() => getThisWeekRange(), []);
  const [rows, setRows] = useState([]);
  const [outlets, setOutlets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [fromDate, setFromDate] = useState(defaultWeekRange.from);
  const [toDate, setToDate] = useState(defaultWeekRange.to);

  const fetchRevenueData = useCallback(async () => {
    setLoading(true);
    try {
      // Keep this page on the exact same revenue definition as Outlet
      // Performance: cash payment + digital payment for each outlet/date.
      const [outletsRes, cashRes, digitalRes] = await Promise.all([
        fetch(`${API_URL}/outlets/all`, { headers: getAuthHeaders() }),
        fetch(`${API_URL}/cash-payments/all?from=${encodeURIComponent(fromDate)}&to=${encodeURIComponent(toDate)}`, { headers: getAuthHeaders() }),
        fetch(`${API_URL}/digital-payments/all?from=${encodeURIComponent(fromDate)}&to=${encodeURIComponent(toDate)}`, { headers: getAuthHeaders() }),
      ]);

      if (![outletsRes, cashRes, digitalRes].every((response) => response.ok)) {
        throw new Error("Failed to load revenue payment records");
      }

      const [outletsData, cashData, digitalData] = await Promise.all([
        outletsRes.json(),
        cashRes.json(),
        digitalRes.json(),
      ]);

      const outletList = Array.isArray(outletsData) ? outletsData : [];
      const cashRows = Array.isArray(cashData) ? cashData : [];
      const digitalRows = Array.isArray(digitalData) ? digitalData : [];

      const outletAliases = new Map();
      outletList.forEach((outlet) => {
        const outletId = outlet?.id;
        if (!outletId) return;
        [outletId, outlet.area, outlet.name].forEach((value) => {
          const key = normalizeOutletKey(value);
          if (key) outletAliases.set(key, outletId);
        });
      });

      const preferredValues = new Map();
      const applyPayments = (records, field) => {
        records.forEach((record) => {
          const date = String(record?.date || "").slice(0, 10);
          if (!date || !record?.outlets || typeof record.outlets !== "object") return;
          const priority = getRecordPriority(record);
          const eventTime = getRecordTime(record);
          Object.entries(record.outlets).forEach(([outletKey, rawValue]) => {
            const outletId = outletAliases.get(normalizeOutletKey(outletKey));
            if (!outletId) return;
            const key = `${field}:${date}:${outletId}`;
            const value = Number(rawValue) || 0;
            const current = preferredValues.get(key);
            if (!current || priority > current.priority || (priority === current.priority && value !== 0 && current.value === 0) || (priority === current.priority && eventTime > current.eventTime)) {
              preferredValues.set(key, { date, outletId, field, value, priority, eventTime });
            }
          });
        });
      };

      applyPayments(cashRows, "cash");
      applyPayments(digitalRows, "digital");

      const dateMap = new Map();
      preferredValues.forEach(({ date, outletId, value }) => {
        if (!dateMap.has(date)) dateMap.set(date, { date, outlets: {} });
        const values = dateMap.get(date).outlets;
        values[outletId] = (Number(values[outletId]) || 0) + value;
      });

      const mergedRows = Array.from(dateMap.values())
        .map((row) => ({
          ...row,
          total: Object.values(row.outlets).reduce((sum, value) => sum + (Number(value) || 0), 0),
        }))
        .sort((a, b) => new Date(a.date) - new Date(b.date));

      setOutlets(outletList);
      setRows(mergedRows);
    } catch (error) {
      console.error("Error fetching daily revenue:", error);
      setRows([]);
      setOutlets([]);
    } finally {
      setLoading(false);
    }
  }, [fromDate, toDate]);

  useEffect(() => {
    fetchRevenueData();
  }, [fetchRevenueData]);

  const filteredRows = useMemo(() => {
    const sorted = [...rows].sort((a, b) => new Date(a.date) - new Date(b.date));
    if (fromDate && toDate) {
      return sorted.filter((row) => {
        const date = new Date(row.date);
        return date >= new Date(fromDate) && date <= new Date(toDate);
      });
    }
    if (fromDate) return sorted.filter((row) => new Date(row.date) >= new Date(fromDate));
    if (toDate) return sorted.filter((row) => new Date(row.date) <= new Date(toDate));
    return sorted;
  }, [rows, fromDate, toDate]);

  const handleDownload = useCallback(() => {
    if (!filteredRows.length) {
      alert("No data available");
      return;
    }

    const data = filteredRows.map((row) => {
      const record = { Date: formatDateDMY(row.date) };
      outlets.forEach((outlet) => {
        const outletId = outlet?.id;
        const label = outlet?.area || outlet?.name || outletId;
        record[label] = Number(row.outlets?.[outletId] ?? 0);
      });
      record.Total = Number(row.total || 0);
      return record;
    });

    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Daily Revenue");
    XLSX.writeFile(workbook, "Daily_Revenue_Report.xlsx");
  }, [filteredRows, outlets]);

  if (loading) {
    return (
      <div className="flex">
        <div className="bg-eggBg min-h-screen p-6 w-full flex items-center justify-center">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#ff7518] mx-auto mb-4"></div>
            <p className="text-gray-600">Loading daily revenue...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex">
      <div className="bg-eggBg min-h-screen p-6 w-full">
        <Topbar />

        <Dailyheader
          title={"Daily Revenue"}
          subtitle={"View outlet-wise daily revenue."}
          dailySalesData={filteredRows}
          fromDate={fromDate}
          toDate={toDate}
          setFromDate={setFromDate}
          setToDate={setToDate}
          allRows={rows}
          onExport={handleDownload}
        />

        <DailyTable
          rows={filteredRows}
          outlets={outlets.map((outlet) => outlet.id)}
          allOutlets={outlets}
          showRupee={true}
        />

        <RevenueAnalytics rows={filteredRows} />
      </div>
    </div>
  );
}
