export const mergeDailyRecords = (records, valuesField = "outlets") => {
  const byDate = new Map();

  (Array.isArray(records) ? records : []).forEach((record) => {
    const date = String(record?.date || "").slice(0, 10);
    if (!date) return;

    const existing = byDate.get(date) || { ...record, date, [valuesField]: {} };
    const mergedValues = { ...(existing[valuesField] || {}) };

    Object.entries(record?.[valuesField] || {}).forEach(([key, value]) => {
      const current = Number(mergedValues[key]) || 0;
      const next = Number(value) || 0;
      if (mergedValues[key] === undefined || next !== 0 || current === 0) {
        mergedValues[key] = value;
      }
    });

    byDate.set(date, {
      ...existing,
      ...record,
      date,
      [valuesField]: mergedValues,
      autoGenerated: Boolean(existing.autoGenerated) && Boolean(record.autoGenerated),
    });
  });

  return Array.from(byDate.values());
};
